### ISSUE TITLE
Many bugs after I type the launch command

### ISSUE THREAD

**Issue by KirjielB** [Lord-of-the-Galaxy/RSSBot#2]
`Discord4J: ERROR INITIALIZING LOGGER!
Discord4J: No SLF4J implementation found, reverting to the internal implementati
on (sx.blah.discord.Discord4J$Discord4JLogger)
Discord4J: It is *highly* recommended to use a fully featured implementation lik
e logback!
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further detail
s.`

Exception in thread "main" java.lang.NoClassDefFoundError: sun/net/spi/nameservi
ce/dns/DNSNameService
        at sx.blah.discord.api.internal.Services.load(Services.java:61)
        at sx.blah.discord.api.internal.DiscordClientImpl.<clinit>(DiscordClient
Impl.java:51)
        at sx.blah.discord.api.ClientBuilder.build(ClientBuilder.java:280)
        at lord_of_galaxy.bot.BotUtils.getBuiltDiscordClient(BotUtils.java:17)
        at lord_of_galaxy.bot.rssbot.RSSBot.<init>(RSSBot.java:75)
        at lord_of_galaxy.bot.rssbot.Launcher.main(Launcher.java:39)
Caused by: java.lang.ClassNotFoundException: sun.net.spi.nameservice.dns.DNSName
Service
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinCla
ssLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(C
lassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 6 more

**Comment by Lord-of-the-Galaxy** [comment]
First, I'm sorry for the late reply.
The first error:
```
Discord4J: ERROR INITIALIZING LOGGER! Discord4J: No SLF4J implementation found, reverting to the internal implementati on (sx.blah.discord.Discord4J$Discord4JLogger) Discord4J: It is *highly* recommended to use a fully featured implementation lik e logback! SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder". SLF4J: Defaulting to no-operation (NOP) logger implementation SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further detail s.
```
is not something to worry about. I've just not bothered to make use of SLF4J.
For the second, can you give me a few more details please? Particularly what OS, which version of Java.
